<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dashboard_app_description'] = 'The Dashboard provides a high-level overview of your system.';
$lang['dashboard_app_name'] = 'Dashboard';
$lang['dashboard_return_to_dashboard'] = 'Return to Dashboard';
