<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dashboard_app_description'] = 'Instrumentpanelen ger dig en översikt av ditt system.';
$lang['dashboard_app_name'] = 'Instrumentpanel';
$lang['dashboard_configure_now'] = 'You have not configured your custom dashboard.  Configure it now or select the default.';
$lang['dashboard_controller_missing'] = 'Dashboard Widget Missing or Uninstalled';
$lang['dashboard_invalid_layout'] = 'Layout is invalid.';
$lang['dashboard_number_of_cols'] = 'Columns - Row';
$lang['dashboard_placeholder'] = 'Placeholder';
$lang['dashboard_return_to_dashboard'] = 'Återvänd till instrumentpanelen';
$lang['dashboard_select_widget'] = 'Widget Selection';
$lang['dashboard_setup_required'] = 'Setup Required';
