<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dashboard_app_description'] = 'Instrumentpanelen ger dig en översikt av ditt system.';
$lang['dashboard_app_name'] = 'Instrumentpanel';
$lang['dashboard_return_to_dashboard'] = 'Återvänd till instrumentpanelen';
