<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dashboard_app_description'] = 'The Dashboard provides a high-level overview of your system.  It is customizable - installed apps may provide Dashboard Widgets that you can add to your layout.';
$lang['dashboard_app_name'] = 'Panel informacyjny';
$lang['dashboard_configure_now'] = 'Nie skonfigurowano jeszcze panelu informacyjnego.  Skonfiguruj go teraz lub wybierz domyślny.';
$lang['dashboard_controller_missing'] = 'Brakuje widgetu panelu informacyjnego lub został on odinstalowany';
$lang['dashboard_controller_not_available'] = 'The app providing this widget has been un-installed and is no longer available.  Use the "Delete" tool to remove this placeholder.';
$lang['dashboard_invalid_layout'] = 'Układ jest nieprawidłowy.';
$lang['dashboard_not_available'] = 'Not Available';
$lang['dashboard_number_of_cols'] = 'Kolumny - Wiersz';
$lang['dashboard_placeholder'] = 'Pole wypełnienia';
$lang['dashboard_select_widget'] = 'Wybór widgetu';
$lang['dashboard_setup_required'] = 'Wymagana konfiguracja';
