<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dashboard_app_description'] = 'Panel informacyjny pokazuje ogólny przegląd systemu.';
$lang['dashboard_app_name'] = 'Panel informacyjny';
$lang['dashboard_return_to_dashboard'] = 'Powrót do Panelu informacyjnego';
